SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[2003] (
		[SegmentId]     [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[Content]       [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[2003] SET (LOCK_ESCALATION = TABLE)
GO
